-- AlterEnum: add new document categories
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SHEET';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'ARCHIVE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'AUDIO';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'VIDEO';
